language: php

php:
  - 5.6
  - 7
  - hhvm
  - hhvm-nightly

before_script:
  - composer self-update
  - composer update

script:
  - ./vendor/bin/phpunit --disallow-test-output --report-useless-tests --coverage-clover ./clover.xml
  - ./finalizer finalizer:check-final-classes src

matrix:
  allow_failures:
    - php: 7
    - php: hhvm
    - php: hhvm-nightly

after_script:
  - sh .travis.coverage.sh
